import { Socket, Server as SocketIOServer } from 'socket.io';
import jwt from 'jsonwebtoken';
import { verifySocketToken } from '../utils/socket-auth';
import { prisma } from '../config/db';
import { waseetAiClient } from '../services/ai/waseet-ai/waseet-ai.client';
import { isSocketAiRateLimited, SOCKET_AI_RATE_LIMIT_MESSAGE } from '../utils/socket-ai-rate-limit';

// Provider onboarding "setup test" on top of WaseetAI (the only AI provider).
//
// Questions are generated by WaseetAI's verified assessment stream
// (streamAssessmentQuestions) from the provider's specialties. WaseetAI never
// sends an answer key, so this gateway cannot know per-question correctness:
// answers are collected in an in-memory per-user session and graded ONCE at the
// end through submitAssessment. setupTestScore is WaseetAI's 0-100 score and
// setupTestStatus becomes COMPLETED (this is a calibration test, never a
// pass/fail gate, so `isPassed` is deliberately ignored). Because the number of
// correct answers is not known, `setup_test:result` has no `correct` field.
//
// Failures never write to the profile: a generation failure creates no session;
// a grading failure keeps the session so the last answer can be re-sent.

export const SETUP_TEST_QUESTION_COUNT = 15;
export const SETUP_TEST_TIME_LIMIT_MINUTES = 15;
const GENERATION_TIMEOUT_MS = 60_000;
const GRADING_TIMEOUT_MS = 45_000;

export const SETUP_TEST_GENERATION_FAILED_MESSAGE =
  'تعذّر إنشاء أسئلة الاختبار حالياً. يرجى المحاولة مرة أخرى بعد قليل.';
export const SETUP_TEST_GRADING_FAILED_MESSAGE =
  'تعذّر تقييم إجاباتك حالياً ولم يتم تسجيل أي نتيجة. يرجى المحاولة مرة أخرى بعد قليل.';
export const SETUP_TEST_NO_SPECIALTY_MESSAGE =
  'يرجى تحديد تخصصك في الملف الشخصي قبل بدء الاختبار.';

interface SessionQuestion {
  id: string; // String(vendor numeric id)
  text: string;
  options: Array<{ id: string; text: string }>;
}

interface SetupTestSession {
  profileId: string;
  vendorAttemptId: string;
  questions: SessionQuestion[];
  currentQIndex: number;
  /** questionId -> optionId (WaseetAI contract) */
  answers: Record<string, string>;
  startedAt: number;
  grading: boolean;
}

export class SetupTestGateway {
  private io: SocketIOServer | null = null;
  private testSessions = new Map<string, SetupTestSession>();

  // The token travels in the event payload: it must pass the same check as a handshake (valid JWT, live session, ACTIVE account).
  private async getUserIdFromToken(token?: string): Promise<string | null> {
    const result = await verifySocketToken(token);
    return result.ok ? result.userId : null;
  }

  private emitQuestion(socket: Socket, session: SetupTestSession): void {
    const q = session.questions[session.currentQIndex];
    if (!q) return;
    // Public shape only: text + option texts. No option ids, no key.
    socket.emit('setup_test:question', {
      id: q.id,
      text: q.text,
      options: q.options.map((o) => o.text),
      index: session.currentQIndex,
      total: session.questions.length
    });
  }

  /** Grades once through WaseetAI and, only on success, writes the profile. */
  private async gradeAndFinish(socket: Socket, userId: string, session: SetupTestSession): Promise<void> {
    if (session.grading) return;
    session.grading = true;
    try {
      const limitSeconds = (SETUP_TEST_TIME_LIMIT_MINUTES + 1) * 60;
      const timeSpentSeconds = Math.max(0, Math.min(limitSeconds, Math.round((Date.now() - session.startedAt) / 1000)));

      let score: number;
      try {
        const graded = await waseetAiClient.submitAssessment(
          session.vendorAttemptId,
          { submittedAnswers: { ...session.answers }, timeSpentSeconds },
          { timeoutMs: GRADING_TIMEOUT_MS }
        );
        if (!graded || typeof graded.score !== 'number' || !Number.isFinite(graded.score) || graded.score < 0 || graded.score > 100) {
          throw new Error('WaseetAI returned an invalid grading result');
        }
        score = graded.score;
      } catch (err: any) {
        console.warn('[SetupTestGateway] grading failed:', err?.code || err?.message);
        socket.emit('setup_test:error', { message: SETUP_TEST_GRADING_FAILED_MESSAGE, retryable: true });
        return; // session kept, nothing written
      }

      try {
        await prisma.providerProfile.update({
          where: { id: session.profileId },
          data: { setupTestScore: score, setupTestStatus: 'COMPLETED' }
        });
      } catch (err: any) {
        console.error('[SetupTestGateway] profile write failed:', err?.message);
        socket.emit('setup_test:error', { message: SETUP_TEST_GRADING_FAILED_MESSAGE, retryable: true });
        return;
      }

      this.testSessions.delete(userId);
      socket.emit('setup_test:result', {
        score,
        total: session.questions.length,
        message: 'تم الانتهاء من الاختبار بنجاح وتم تسجيل نتيجتك لتصنيف مستواك.'
      });
    } finally {
      session.grading = false;
    }
  }

  public register(socket: Socket, io?: SocketIOServer): void {
    if (io) this.io = io;

    socket.on('setup_test:init', async (payload: { token: string }) => {
      let onDisconnect: (() => void) | null = null;
      try {
        const userId = await this.getUserIdFromToken(payload?.token);
        if (!userId) {
          socket.emit('setup_test:error', { message: 'رمز الحساب غير صالح أو منتهي الصلاحية.' });
          return;
        }

        if (isSocketAiRateLimited(userId)) {
          socket.emit('setup_test:error', { message: SOCKET_AI_RATE_LIMIT_MESSAGE });
          return;
        }

        // Registered before the DB lookup so a disconnect during the lookup
        // or the WaseetAI stream is honored.
        const abortController = new AbortController();
        onDisconnect = () => abortController.abort();
        socket.once('disconnect', onDisconnect);

        const profile = await prisma.providerProfile.findUnique({ where: { userId } });
        if (!profile) {
          socket.emit('setup_test:error', { message: 'الملف الشخصي لمقدم الخدمة غير موجود.' });
          return;
        }

        if (profile.setupTestStatus === 'BANNED' || profile.setupTestBannedUntil) {
          await prisma.providerProfile.update({
            where: { id: profile.id },
            data: { setupTestStatus: 'PENDING', setupTestBannedUntil: null, setupTestCheatAttempts: 0 }
          });
        }

        // The specialty comes from our own DB; nothing is invented.
        const mainSpec = (profile.mainSpecialty || profile.industry || '').trim();
        const subSpecs = (Array.isArray(profile.subSpecialties) ? profile.subSpecialties : [])
          .filter((s: unknown): s is string => typeof s === 'string' && s.trim().length > 0)
          .map((s: string) => s.trim());
        if (!mainSpec && subSpecs.length === 0) {
          socket.emit('setup_test:error', { message: SETUP_TEST_NO_SPECIALTY_MESSAGE });
          return;
        }
        const specialtyName = mainSpec && subSpecs.length > 0
          ? `${mainSpec} (${subSpecs.join('، ')})`
          : (mainSpec || subSpecs.join('، '));

        socket.emit('setup_test:generating', { message: 'جاري إنشاء الاختبار المخصص لك بناءً على تخصصاتك باستخدام الذكاء الاصطناعي...' });

        const questions: SessionQuestion[] = [];
        const vendorAttemptIds = new Set<string>();
        let ready: { attemptId: string; totalQuestions: number } | null = null;
        try {
          for await (const event of waseetAiClient.streamAssessmentQuestions({
            providerSpecialtyId: profile.id,
            specialtyName,
            questionCount: SETUP_TEST_QUESTION_COUNT,
            timeLimitMinutes: SETUP_TEST_TIME_LIMIT_MINUTES
          }, { signal: abortController.signal, timeoutMs: GENERATION_TIMEOUT_MS })) {
            if (event.type === 'question') {
              const q = event.question;
              if (
                !q || typeof q.id !== 'number' || typeof q.textAr !== 'string' || !q.textAr.trim() ||
                !Array.isArray(q.options) || q.options.length < 2 ||
                !q.options.every((o) => o && typeof o.id === 'string' && o.id && typeof o.text === 'string')
              ) {
                throw new Error('invalid question from WaseetAI');
              }
              vendorAttemptIds.add(event.attemptId);
              questions.push({ id: String(q.id), text: q.textAr, options: q.options.map((o) => ({ id: o.id, text: o.text })) });
            } else if (event.type === 'assessment_ready') {
              ready = { attemptId: event.attemptId, totalQuestions: event.totalQuestions };
            }
          }
          if (
            !ready || questions.length === 0 || ready.totalQuestions !== questions.length ||
            vendorAttemptIds.size !== 1 || !vendorAttemptIds.has(ready.attemptId) ||
            new Set(questions.map((q) => q.id)).size !== questions.length
          ) {
            throw new Error('WaseetAI assessment stream was incomplete or inconsistent');
          }
        } catch (aiErr: any) {
          if (abortController.signal.aborted) return; // client gone
          console.warn('[SetupTestGateway] WaseetAI generation failed:', aiErr?.code || aiErr?.message);
          socket.emit('setup_test:error', { message: SETUP_TEST_GENERATION_FAILED_MESSAGE });
          return;
        }

        if (abortController.signal.aborted) return;

        this.testSessions.set(userId, {
          profileId: profile.id,
          vendorAttemptId: ready!.attemptId,
          questions,
          currentQIndex: 0,
          answers: {},
          startedAt: Date.now(),
          grading: false
        });

        socket.emit('setup_test:ready', { totalQuestions: questions.length });
      } catch (err: any) {
        console.error('[SetupTestGateway Init Error]:', err);
        socket.emit('setup_test:error', { message: 'حدث خطأ أثناء إنشاء أسئلة الاختبار.' });
      } finally {
        if (onDisconnect) socket.off('disconnect', onDisconnect);
      }
    });

    socket.on('setup_test:get_question', async (payload: { token: string }) => {
      try {
        const userId = await this.getUserIdFromToken(payload?.token);
        if (!userId) return;
        const session = this.testSessions.get(userId);
        if (!session) return;
        if (session.currentQIndex < session.questions.length) this.emitQuestion(socket, session);
      } catch (e) {
        console.error('[SetupTestGateway get_question Error]:', e);
      }
    });

    socket.on('setup_test:answer', async (payload: { token: string; questionId: string; selectedIndex: number }) => {
      try {
        const userId = await this.getUserIdFromToken(payload?.token);
        if (!userId) return;
        const session = this.testSessions.get(userId);
        if (!session || session.grading) return;

        const total = session.questions.length;
        const finished = session.currentQIndex >= total;
        // After a failed grading the session sits at the end; re-sending the
        // last answer retries the (single) grading call.
        const idx = finished ? total - 1 : session.currentQIndex;
        const q = session.questions[idx];
        if (!q || String(payload?.questionId) !== q.id) return;

        const sel = payload.selectedIndex;
        if (!Number.isInteger(sel) || sel < 0 || sel >= q.options.length) return;

        session.answers[q.id] = q.options[sel].id;

        if (!finished) {
          session.currentQIndex++;
          if (session.currentQIndex < total) {
            this.emitQuestion(socket, session);
            return;
          }
        }
        await this.gradeAndFinish(socket, userId, session);
      } catch (e) {
        console.error('[SetupTestGateway answer Error]:', e);
      }
    });

    socket.on('setup_test:anti_cheat', async (payload: { token: string; type: string }) => {
      // Anti-cheat ban is currently disabled for testing purposes
      console.log(`[AntiCheat Info]: event received for testing (${payload?.type})`);
    });
  }
}

export const setupTestGateway = new SetupTestGateway();
export const registerSetupTestGateway = (socket: Socket, io?: SocketIOServer) => setupTestGateway.register(socket, io);
