ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'PENDING_CLIENT_SIGNATURE';
ALTER TYPE "ContractStatus" ADD VALUE IF NOT EXISTS 'PENDING_PROVIDER_SIGNATURE';

ALTER TABLE "otp_verifications"
ADD COLUMN IF NOT EXISTS "context" JSONB,
ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "contracts"
ADD COLUMN IF NOT EXISTS "clientSignedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "providerSignedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "clientSignatureHash" TEXT,
ADD COLUMN IF NOT EXISTS "providerSignatureHash" TEXT,
ADD COLUMN IF NOT EXISTS "termsVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "contracts" ALTER COLUMN "signedAt" DROP DEFAULT;

ALTER TABLE "escrows"
ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT,
ADD COLUMN IF NOT EXISTS "paymentReference" TEXT,
ADD COLUMN IF NOT EXISTS "fundedAt" TIMESTAMP(3);
