import { Request, Response, NextFunction } from 'express';
import { projectService } from '../services/project.service';
import { createProjectSchema } from '../dtos/project.dto';

export class ProjectController {
  
  public async createProject(req: Request, res: Response, next: NextFunction) {
    try {
      // Access the parsed user payload generated by authenticate middleware
      const userId = req.user!.userId;

      const validatedData = createProjectSchema.parse(req.body);
      
      const project = await projectService.createProject(userId, validatedData);
      
      res.status(201).json({
        success: true,
        message: 'تم نشر الطلب بنجاح',
        data: project
      });
    } catch (error) {
      next(error);
    }
  }
  public async getMyRequests(req: Request, res: Response, next: NextFunction) {
    try {
      const userId = req.user!.userId;
      const result = await projectService.getMyRequests(userId);
      
      res.status(200).json({
        success: true,
        ...result
      });
    } catch (error) {
      next(error);
    }
  }

  public async getSummary(req: Request, res: Response, next: NextFunction) {
    try {
      const id = req.params.id as string;
      const user = req.user!;
      const summary = await projectService.getProjectSummary(id, {
        userId: user.userId || user.id,
        accountType: user.accountType,
        activeRole: user.activeRole,
        roles: user.roles
      });

      res.status(200).json({
        success: true,
        data: summary
      });
    } catch (error) {
      next(error);
    }
  }
}

export const projectController = new ProjectController();

