-- ============================================================================
-- NOT EXECUTED.  Generated by `prisma migrate diff --from-config-datasource
-- --to-schema prisma/schema.prisma --script` using the schema at main
-- e0300ee against a restore of the G4 backup (waseetai-prod-db-20261002-
-- 223032Z.dump).  Contains no credentials.
--
-- Statement order inside each part is exactly Prisma's order; only the
-- grouping/banners were added.  Apply with:  psql --single-transaction
-- -v ON_ERROR_STOP=1 -f <file>   (see prod-schema-apply-plan-e0300ee.md)
-- ============================================================================

-- This is the reference copy: PART A (sections 1-5) followed by PART B
-- (section 6, DROPS).  Run the two parts as separate transactions
-- (…-part-a-additive.sql then, much later, …-part-b-drops.sql).

-- Fail fast instead of queueing behind long locks, and keep the transaction short.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

-- ############################################################################
-- SECTION 1: CREATE TYPE / ALTER TYPE (enums)
-- ############################################################################

-- CreateEnum
CREATE TYPE "ApprovalStatus" AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "SpecialOfferType" AS ENUM ('BUNDLE', 'DIRECT_DISCOUNT');

-- CreateEnum
CREATE TYPE "SupportTicketStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'AWAITING_CUSTOMER', 'RESOLVED', 'CLOSED');

-- CreateEnum
CREATE TYPE "AmendmentRequesterRole" AS ENUM ('CLIENT', 'PROVIDER');

-- CreateEnum
CREATE TYPE "AmendmentType" AS ENUM ('SCOPE', 'BUDGET', 'DURATION', 'MIXED');

-- CreateEnum
CREATE TYPE "AmendmentStatus" AS ENUM ('PENDING_OTHER_PARTY', 'APPROVED', 'REJECTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "PayoutAttemptStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED');

-- CreateEnum
CREATE TYPE "PaypalWebhookEventStatus" AS ENUM ('RECEIVED', 'PROCESSED', 'FAILED');

-- CreateEnum
CREATE TYPE "PaypalPaymentStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "TeamMemberType" AS ENUM ('PROVIDER', 'EMPLOYEE');

-- CreateEnum
CREATE TYPE "TeamMemberStatus" AS ENUM ('ACTIVE', 'PENDING', 'INACTIVE');

-- AlterEnum
ALTER TYPE "CommissionType" ADD VALUE 'STAGE_RELEASE';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "WithdrawalStatus" ADD VALUE 'PROCESSING';
ALTER TYPE "WithdrawalStatus" ADD VALUE 'REVERSED';


-- ############################################################################
-- SECTION 2: CREATE TABLE (10 new tables)
-- ############################################################################

-- CreateTable
CREATE TABLE "special_offers" (
    "id" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "type" "SpecialOfferType" NOT NULL,
    "name" TEXT NOT NULL,
    "primaryServiceId" TEXT,
    "beneficiaryServiceId" TEXT,
    "targetServiceId" TEXT,
    "discountValue" DOUBLE PRECISION NOT NULL,
    "validityDays" INTEGER,
    "startAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3),
    "badgeText" TEXT NOT NULL,
    "customerMessage" TEXT,
    "internalNote" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "usedCount" INTEGER NOT NULL DEFAULT 0,
    "assignedToTeamMemberId" TEXT,
    "createdByTeamMemberId" TEXT,
    "approvalStatus" "ApprovalStatus" NOT NULL DEFAULT 'NONE',
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "special_offers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "special_offer_redemptions" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "special_offer_redemptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_preferences" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "support_tickets" (
    "id" TEXT NOT NULL,
    "ticketNumber" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'عادية',
    "description" TEXT NOT NULL,
    "relatedOrder" TEXT,
    "relatedProject" TEXT,
    "relatedMember" TEXT,
    "ccEmail" TEXT,
    "status" "SupportTicketStatus" NOT NULL DEFAULT 'OPEN',
    "resolvedAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "support_tickets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "support_ticket_messages" (
    "id" TEXT NOT NULL,
    "ticketId" TEXT NOT NULL,
    "senderId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "support_ticket_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_amendments" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "contractId" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "requestedById" TEXT NOT NULL,
    "requestedByRole" "AmendmentRequesterRole" NOT NULL,
    "type" "AmendmentType" NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "budgetDelta" DOUBLE PRECISION,
    "durationDeltaDays" INTEGER,
    "status" "AmendmentStatus" NOT NULL DEFAULT 'PENDING_OTHER_PARTY',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "respondedAt" TIMESTAMP(3),

    CONSTRAINT "project_amendments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payout_attempts" (
    "id" TEXT NOT NULL,
    "withdrawalId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "attemptNumber" INTEGER NOT NULL,
    "senderBatchId" TEXT NOT NULL,
    "payoutBatchId" TEXT,
    "payoutItemId" TEXT,
    "status" "PayoutAttemptStatus" NOT NULL DEFAULT 'PENDING',
    "failureReason" TEXT,
    "paypalTerminalStatus" TEXT,
    "rawResponse" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),

    CONSTRAINT "payout_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "paypal_webhook_events" (
    "id" TEXT NOT NULL,
    "paypalEventId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "resourceType" TEXT,
    "paypalCreateTime" TIMESTAMP(3),
    "payoutAttemptId" TEXT,
    "status" "PaypalWebhookEventStatus" NOT NULL DEFAULT 'RECEIVED',
    "rawEvent" JSONB,
    "processedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "paypal_webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "paypal_payments" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "reference" TEXT NOT NULL,
    "paypalOrderId" TEXT NOT NULL,
    "paypalCaptureId" TEXT,
    "amount" DECIMAL(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "status" "PaypalPaymentStatus" NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "paypal_payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_team_members" (
    "id" TEXT NOT NULL,
    "companyOwnerId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "jobTitle" TEXT NOT NULL,
    "memberType" "TeamMemberType" NOT NULL,
    "status" "TeamMemberStatus" NOT NULL DEFAULT 'PENDING',
    "avatarUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_team_members_pkey" PRIMARY KEY ("id")
);


-- ############################################################################
-- SECTION 3: ALTER TABLE ... ADD COLUMN (7 existing tables; one default change)
-- ############################################################################

-- AlterTable
ALTER TABLE "affiliate_profiles" ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "minimumPayoutAmount" SET DEFAULT 300.0;

-- AlterTable
ALTER TABLE "commission_logs" ADD COLUMN     "appliedPercentage" DOUBLE PRECISION NOT NULL,
ADD COLUMN     "baseAmount" DOUBLE PRECISION NOT NULL,
ADD COLUMN     "level" INTEGER NOT NULL,
ADD COLUMN     "referredUserId" TEXT NOT NULL,
ADD COLUMN     "sourceProjectId" TEXT,
ADD COLUMN     "sourceStageId" TEXT;

-- AlterTable
ALTER TABLE "coupons" ADD COLUMN     "approvalStatus" "ApprovalStatus" NOT NULL DEFAULT 'NONE',
ADD COLUMN     "assignedToTeamMemberId" TEXT,
ADD COLUMN     "createdByTeamMemberId" TEXT,
ADD COLUMN     "excludedServiceIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "internalNote" TEXT,
ADD COLUMN     "rejectionReason" TEXT;

-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "assignedEmployeeId" TEXT;

-- AlterTable
ALTER TABLE "provider_profiles" ADD COLUMN     "paypalPayoutEmail" TEXT;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "marketingMonthlySpendCap" DOUBLE PRECISION,
ADD COLUMN     "phoneOtpEnabled" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "withdrawals" ADD COLUMN     "paypalEmail" TEXT;


-- ############################################################################
-- SECTION 4: INDEXES (36; one UNIQUE on commission_logs needs the new sourceStageId column from section 3)
-- ############################################################################

-- CreateIndex
CREATE INDEX "special_offers_providerId_approvalStatus_idx" ON "special_offers"("providerId", "approvalStatus");

-- CreateIndex
CREATE INDEX "special_offers_primaryServiceId_idx" ON "special_offers"("primaryServiceId");

-- CreateIndex
CREATE INDEX "special_offers_beneficiaryServiceId_idx" ON "special_offers"("beneficiaryServiceId");

-- CreateIndex
CREATE INDEX "special_offers_targetServiceId_idx" ON "special_offers"("targetServiceId");

-- CreateIndex
CREATE INDEX "special_offers_assignedToTeamMemberId_idx" ON "special_offers"("assignedToTeamMemberId");

-- CreateIndex
CREATE INDEX "special_offers_createdByTeamMemberId_idx" ON "special_offers"("createdByTeamMemberId");

-- CreateIndex
CREATE INDEX "special_offer_redemptions_offerId_userId_idx" ON "special_offer_redemptions"("offerId", "userId");

-- CreateIndex
CREATE INDEX "special_offer_redemptions_orderId_idx" ON "special_offer_redemptions"("orderId");

-- CreateIndex
CREATE UNIQUE INDEX "special_offer_redemptions_offerId_userId_orderId_key" ON "special_offer_redemptions"("offerId", "userId", "orderId");

-- CreateIndex
CREATE UNIQUE INDEX "notification_preferences_userId_key" ON "notification_preferences"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "support_tickets_ticketNumber_key" ON "support_tickets"("ticketNumber");

-- CreateIndex
CREATE INDEX "support_tickets_userId_status_idx" ON "support_tickets"("userId", "status");

-- CreateIndex
CREATE INDEX "support_ticket_messages_ticketId_createdAt_idx" ON "support_ticket_messages"("ticketId", "createdAt");

-- CreateIndex
CREATE INDEX "project_amendments_clientId_status_idx" ON "project_amendments"("clientId", "status");

-- CreateIndex
CREATE INDEX "project_amendments_providerId_status_idx" ON "project_amendments"("providerId", "status");

-- CreateIndex
CREATE INDEX "project_amendments_contractId_idx" ON "project_amendments"("contractId");

-- CreateIndex
CREATE UNIQUE INDEX "payout_attempts_senderBatchId_key" ON "payout_attempts"("senderBatchId");

-- CreateIndex
CREATE UNIQUE INDEX "payout_attempts_payoutItemId_key" ON "payout_attempts"("payoutItemId");

-- CreateIndex
CREATE INDEX "payout_attempts_withdrawalId_status_idx" ON "payout_attempts"("withdrawalId", "status");

-- CreateIndex
CREATE INDEX "payout_attempts_status_createdAt_idx" ON "payout_attempts"("status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "payout_attempts_withdrawalId_attemptNumber_key" ON "payout_attempts"("withdrawalId", "attemptNumber");

-- CreateIndex
CREATE UNIQUE INDEX "active_attempt_unique" ON "payout_attempts"("withdrawalId") WHERE (status IN ('PENDING','PROCESSING'));

-- CreateIndex
CREATE UNIQUE INDEX "paypal_webhook_events_paypalEventId_key" ON "paypal_webhook_events"("paypalEventId");

-- CreateIndex
CREATE INDEX "paypal_webhook_events_payoutAttemptId_idx" ON "paypal_webhook_events"("payoutAttemptId");

-- CreateIndex
CREATE INDEX "paypal_webhook_events_status_createdAt_idx" ON "paypal_webhook_events"("status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "paypal_payments_reference_key" ON "paypal_payments"("reference");

-- CreateIndex
CREATE UNIQUE INDEX "paypal_payments_paypalOrderId_key" ON "paypal_payments"("paypalOrderId");

-- CreateIndex
CREATE UNIQUE INDEX "paypal_payments_paypalCaptureId_key" ON "paypal_payments"("paypalCaptureId");

-- CreateIndex
CREATE INDEX "paypal_payments_userId_createdAt_idx" ON "paypal_payments"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "company_team_members_companyOwnerId_memberType_status_idx" ON "company_team_members"("companyOwnerId", "memberType", "status");

-- CreateIndex
CREATE UNIQUE INDEX "company_team_members_companyOwnerId_email_key" ON "company_team_members"("companyOwnerId", "email");

-- CreateIndex
CREATE UNIQUE INDEX "commission_logs_affiliateId_referralId_type_sourceStageId_key" ON "commission_logs"("affiliateId", "referralId", "type", "sourceStageId");

-- CreateIndex
CREATE INDEX "coupons_assignedToTeamMemberId_idx" ON "coupons"("assignedToTeamMemberId");

-- CreateIndex
CREATE INDEX "coupons_createdByTeamMemberId_idx" ON "coupons"("createdByTeamMemberId");

-- CreateIndex
CREATE INDEX "coupons_providerId_approvalStatus_idx" ON "coupons"("providerId", "approvalStatus");

-- CreateIndex
CREATE INDEX "projects_assignedEmployeeId_idx" ON "projects"("assignedEmployeeId");


-- ############################################################################
-- SECTION 5: FOREIGN KEYS (25 new)
-- ############################################################################

-- AddForeignKey
ALTER TABLE "projects" ADD CONSTRAINT "projects_assignedEmployeeId_fkey" FOREIGN KEY ("assignedEmployeeId") REFERENCES "company_team_members"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_assignedToTeamMemberId_fkey" FOREIGN KEY ("assignedToTeamMemberId") REFERENCES "company_team_members"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_createdByTeamMemberId_fkey" FOREIGN KEY ("createdByTeamMemberId") REFERENCES "company_team_members"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_primaryServiceId_fkey" FOREIGN KEY ("primaryServiceId") REFERENCES "service_catalogs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_beneficiaryServiceId_fkey" FOREIGN KEY ("beneficiaryServiceId") REFERENCES "service_catalogs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_targetServiceId_fkey" FOREIGN KEY ("targetServiceId") REFERENCES "service_catalogs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_assignedToTeamMemberId_fkey" FOREIGN KEY ("assignedToTeamMemberId") REFERENCES "company_team_members"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offers" ADD CONSTRAINT "special_offers_createdByTeamMemberId_fkey" FOREIGN KEY ("createdByTeamMemberId") REFERENCES "company_team_members"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offer_redemptions" ADD CONSTRAINT "special_offer_redemptions_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "special_offers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offer_redemptions" ADD CONSTRAINT "special_offer_redemptions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "special_offer_redemptions" ADD CONSTRAINT "special_offer_redemptions_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "support_tickets" ADD CONSTRAINT "support_tickets_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "support_ticket_messages" ADD CONSTRAINT "support_ticket_messages_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "support_tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "support_ticket_messages" ADD CONSTRAINT "support_ticket_messages_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_amendments" ADD CONSTRAINT "project_amendments_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_amendments" ADD CONSTRAINT "project_amendments_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_amendments" ADD CONSTRAINT "project_amendments_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_amendments" ADD CONSTRAINT "project_amendments_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "project_amendments" ADD CONSTRAINT "project_amendments_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payout_attempts" ADD CONSTRAINT "payout_attempts_withdrawalId_fkey" FOREIGN KEY ("withdrawalId") REFERENCES "withdrawals"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "paypal_webhook_events" ADD CONSTRAINT "paypal_webhook_events_payoutAttemptId_fkey" FOREIGN KEY ("payoutAttemptId") REFERENCES "payout_attempts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "paypal_payments" ADD CONSTRAINT "paypal_payments_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_team_members" ADD CONSTRAINT "company_team_members_companyOwnerId_fkey" FOREIGN KEY ("companyOwnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

====================

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

-- ############################################################################
-- SECTION 6: DROPS (destructive, deferred): 6 foreign keys, 4 legacy quiz tables, 1 enum type
-- ############################################################################

-- DropForeignKey
ALTER TABLE "specialty_test_sessions" DROP CONSTRAINT "specialty_test_sessions_providerSpecialtyId_fkey";

-- DropForeignKey
ALTER TABLE "specialty_test_sessions" DROP CONSTRAINT "specialty_test_sessions_userId_fkey";

-- DropForeignKey
ALTER TABLE "specialty_tests" DROP CONSTRAINT "specialty_tests_specialtyId_fkey";

-- DropForeignKey
ALTER TABLE "test_question_submissions" DROP CONSTRAINT "test_question_submissions_sessionId_fkey";

-- DropForeignKey
ALTER TABLE "test_submissions" DROP CONSTRAINT "test_submissions_providerSpecialtyId_fkey";

-- DropForeignKey
ALTER TABLE "test_submissions" DROP CONSTRAINT "test_submissions_testId_fkey";

-- DropTable
DROP TABLE "specialty_test_sessions";

-- DropTable
DROP TABLE "specialty_tests";

-- DropTable
DROP TABLE "test_question_submissions";

-- DropTable
DROP TABLE "test_submissions";

-- DropEnum
DROP TYPE "TestSessionStatus";

