-- ============================================================================
-- NOT EXECUTED.  Generated by `prisma migrate diff --from-config-datasource
-- --to-schema prisma/schema.prisma --script` using the schema at main
-- e0300ee against a restore of the G4 backup (waseetai-prod-db-20261002-
-- 223032Z.dump).  Contains no credentials.
--
-- Statement order inside each part is exactly Prisma's order; only the
-- grouping/banners were added.  Apply SEPARATELY and LATER with:  psql --single-transaction
-- -v ON_ERROR_STOP=1 -f <file>   (see prod-schema-apply-plan-e0300ee.md)
-- ============================================================================

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

-- ############################################################################
-- SECTION 6: DROPS (destructive, deferred): 6 foreign keys, 4 legacy quiz tables, 1 enum type
-- ############################################################################

-- DropForeignKey
ALTER TABLE "specialty_test_sessions" DROP CONSTRAINT "specialty_test_sessions_providerSpecialtyId_fkey";

-- DropForeignKey
ALTER TABLE "specialty_test_sessions" DROP CONSTRAINT "specialty_test_sessions_userId_fkey";

-- DropForeignKey
ALTER TABLE "specialty_tests" DROP CONSTRAINT "specialty_tests_specialtyId_fkey";

-- DropForeignKey
ALTER TABLE "test_question_submissions" DROP CONSTRAINT "test_question_submissions_sessionId_fkey";

-- DropForeignKey
ALTER TABLE "test_submissions" DROP CONSTRAINT "test_submissions_providerSpecialtyId_fkey";

-- DropForeignKey
ALTER TABLE "test_submissions" DROP CONSTRAINT "test_submissions_testId_fkey";

-- DropTable
DROP TABLE "specialty_test_sessions";

-- DropTable
DROP TABLE "specialty_tests";

-- DropTable
DROP TABLE "test_question_submissions";

-- DropTable
DROP TABLE "test_submissions";

-- DropEnum
DROP TYPE "TestSessionStatus";

