#!/bin/bash
# DEV ONLY. NOT a migration: backup + read-only inventory + DRY RUN, then it STOPS. usage: bash 00-dev-backup-and-dryrun.sh   (from this folder, on the Mac)
# Order: 1) pg_dump of the affected tables -> /root/retired/ (mode 600)  2) read-only inventory -> /root/retired/ (mode 600)  3) dry run (prints COUNTS only).
# Nothing in the database or in Cloudinary is written or renamed. The real step (02 --execute, 03, update) needs the owner's explicit approval.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
TS=$(date -u +%Y%m%dT%H%M%SZ)
SSHC=(ssh -i "$HOME/.ssh/waseet_vps_ed25519" -o IdentitiesOnly=yes root@46.202.173.40)
PG=wasit-pg-dev; DB=waseetai_db_dev
[ "$DB" = waseetai_db_dev ] || { echo "STOP: dev database only"; exit 1; }

echo "## 1 backup (pg_dump -Fc of the affected tables)"
"${SSHC[@]}" "set -euo pipefail; umask 077; mkdir -p /root/retired; chmod 700 /root/retired
  DUMP=/root/retired/pre-kyc-migration-dev-$TS.dump
  docker exec $PG sh -c 'pg_dump -U \"\$POSTGRES_USER\" -Fc -d $DB -t client_profiles -t provider_profiles -t client_onboarding -t users -t proof_attachments -t affiliate_profiles -t provider_accreditation_proofs -t certificates' > \$DUMP
  chmod 600 \$DUMP
  echo file: \$DUMP; stat -c 'mode %a size %s bytes' \$DUMP; sha256sum \$DUMP | cut -d' ' -f1 | sed 's/^/sha256 /'
  docker exec -i $PG pg_restore -l < \$DUMP | grep -c 'TABLE DATA' | sed 's/^/tables with data in the dump: /'"

echo "## 2 read-only inventory (kept on the server, not printed)"
"${SSHC[@]}" "umask 077; mkdir -p /root/retired/kyc-migration-$TS; chmod 700 /root/retired/kyc-migration-$TS"
cat "$HERE/01-inventory.sql" | "${SSHC[@]}" "docker exec -i -e PGOPTIONS='-c default_transaction_read_only=on' $PG sh -c 'psql -U \"\$POSTGRES_USER\" -d $DB -At -F \",\"' > /root/retired/kyc-migration-$TS/inventory.csv; chmod 600 /root/retired/kyc-migration-$TS/inventory.csv; echo inventory rows: \$(( \$(wc -l < /root/retired/kyc-migration-$TS/inventory.csv) - 1 ))"

echo "## 3 dry run (no Cloudinary call, counts only)"
tar -C "$HERE" -cf - lib.js 02-rename-to-authenticated.js | "${SSHC[@]}" "tar -x -C /root/retired/kyc-migration-$TS"
"${SSHC[@]}" "cd /root/retired/kyc-migration-$TS && chmod 600 lib.js 02-rename-to-authenticated.js && CLOUDINARY_CLOUD_NAME=\$(docker exec waseetai-backend-dev printenv CLOUDINARY_CLOUD_NAME) node 02-rename-to-authenticated.js inventory.csv; chmod 600 mapping.dry.csv; echo 'details (not printed): /root/retired/kyc-migration-$TS/mapping.dry.csv'; echo 'rollback files are generated by 03 only after the real run; rollback = 04-rollback.js + 04-rollback-db.NOT-EXECUTED.sql or pg_restore of the dump above'"
echo "## STOP — nothing was renamed or written. Waiting for the owner's explicit approval."
